package com.misaka10843.createrailwayannouncer.announcement;

public enum AnnouncementEventType {
    ONBOARD_NEXT_STOP,
    ONBOARD_APPROACHING,
    ONBOARD_ARRIVED,
    ONBOARD_DEPARTING,
    ONBOARD_TERMINAL,

    PLATFORM_APPROACH,
    PLATFORM_ARRIVAL,
    PLATFORM_PRE_DEPARTURE,
    PLATFORM_DEPARTURE_MELODY,
    PLATFORM_DOOR_CLOSING,
    PLATFORM_DEPARTED,

    DOOR_OPENING,
    DOOR_CLOSING,
    SAFETY_NOTICE
}
